export const COMPANY_INFO = {
  legal_name: 'ИП «SMM DRUG»',
  short_name: 'SMM DRUG',
  bin: '000527501224',
  address: 'г.Алматы, Бостандыкский район, мкр. Алмагуль, 27',
  legal_address: 'г.Алматы, Бостандыкский район, мкр. Алмагуль, 27',
  director: 'Маликов Олег Михаилович',
  director_position: 'Директор',
  director_basis: 'Устава',
  bank: 'АО "Jusan Bank"',
  iban: 'KZ448562204110732118',
  bik: 'KCJBKZKX',
  phone: '8 (707) 521 05 65',
  email: 'smmdrug@gmail.com',
  website: '',
};

export const EXECUTOR_FIELDS_MAPPING: Record<string, keyof typeof COMPANY_INFO> = {
  executor_name: 'legal_name',
  executor_company: 'legal_name',
  executor_short_name: 'short_name',
  executor_bin: 'bin',
  executor_inn: 'bin',
  executor_address: 'address',
  executor_legal_address: 'legal_address',
  executor_director: 'director',
  executor_ceo: 'director',
  executor_position: 'director_position',
  executor_basis: 'director_basis',
  executor_bank: 'bank',
  executor_iban: 'iban',
  executor_account: 'iban',
  executor_bik: 'bik',
  executor_phone: 'phone',
  executor_email: 'email',
  executor_website: 'website',
};
