/*
  # Отключение RLS для всех таблиц

  Полностью отключаем RLS для всех таблиц системы, так как используется
  простая авторизация через localStorage без Supabase Auth.
  
  Фильтрация по организациям происходит на уровне приложения.
*/

-- Отключаем RLS для всех таблиц
ALTER TABLE activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE addon_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE calculator_services DISABLE ROW LEVEL SECURITY;
ALTER TABLE company_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE contract_instances DISABLE ROW LEVEL SECURITY;
ALTER TABLE contract_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE crm_activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE crm_activity_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE executor_company_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_access DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_project_access DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_users DISABLE ROW LEVEL SECURITY;
ALTER TABLE job_titles DISABLE ROW LEVEL SECURITY;
ALTER TABLE kpi_presets DISABLE ROW LEVEL SECURITY;
ALTER TABLE notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE organization_subscriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_expenses_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_legal_documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_level1_stage_status DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_roadmap_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE project_roadmap_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_stage_level1 DISABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_template_stages DISABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_template_tasks DISABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE salary_schemes DISABLE ROW LEVEL SECURITY;
ALTER TABLE service_calculator_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE services DISABLE ROW LEVEL SECURITY;
ALTER TABLE subscription_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE usage_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE wazzup_channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_chats DISABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE whatsapp_templates DISABLE ROW LEVEL SECURITY;
